# -*- coding: utf-8 -*-
"""toy_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hc4iPSyEyWOei5QTPCIL7eAgtOaBHi9e
"""

#map style for RGCN

import pickle
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/MyDrive/metabolic_graphs/1_toy_graphs.pickle', 'rb') as handle:
    graphs= pickle.load(handle)

with open('/content/drive/MyDrive/metabolic_graphs/1_node_features.pickle', 'rb') as handle:
    features= pickle.load(handle)

RAG = pd.read_csv("/content/drive/MyDrive/metabolic_graphs/toy_adjacency_matrix.csv", index_col=0)

# RAG

# list(graphs.items())[0]

# list(features.items())[0]

